[package]
name = "alias_wrapper"
version = "0.6.0"
edition = "2024"

[dependencies]
alias_lib = { path = "../alias_lib" }
winreg = "0.55.0"

[dev-dependencies]
serial_test = "3.1.1"
alias_nuke = { path = "../alias_nuke" }