# alias_lib/Cargo.toml
[package]
name = "alias_lib"
version = "0.8.0"
edition = "2024"

[dev-dependencies]
# This ensures alias_nuke is built before any lib tests run
alias_nuke = { path = "../alias_nuke" }
serial_test = "3.1.1"
ctor = "0.6.3"
function_name = "0.3.0"

[dependencies]
tempfile = "3.24.0"
shlex = "1.3.0"
lazy_static = "1.5.0"
serial_test = "3.2.0"
function_name = "0.3.0"


[features]
test-utils = []