[package]
name = "alias"
version = "6.0.1"
edition = "2024"

[dependencies]
alias_lib = { path = "../alias_lib" }
alias_win32 = { path = "../alias_win32" }
alias_wrapper = { path = "../alias_wrapper" }
windows-sys = { version = "0.61.2", features = [
    "Win32_System_Console",
    "Win32_System_Registry",
    "Win32_Foundation"
] }
